name: Bug report
description: Create a report to help us improve something that is not working correctly
title: "Bug: <brief description of the issue>"
labels: "Status: Needs Review, Type: Bug"
body:
  - type: markdown
    attributes:
      value: Thank you for taking the time to submit a bug report to The Odin Project. In order to get issues closed in a reasonable amount of time, you must include a baseline of information about the bug in question.
  - type: checkboxes
    id: checks
    attributes:
      label: Checks
      description: Please fill out the following checkboxes
      options:
        - label: I have thoroughly read and understand [The Odin Project Contributing Guide](https://github.com/TheOdinProject/.github/blob/main/CONTRIBUTING.md)
          required: true
        - label: "The title of this issue follows the `Bug: brief description of bug` format, e.g. `Bug: Lesson complete button does not update on click`"
          required: true
        - label: Would you like to work on this issue?
          required: false
  - type: textarea
    id: bug-report
    attributes:
      label: Bug description
      description: A clear and concise description of what the bug is. Include any screenshots that may help show the bug in action.
      placeholder: ex 'When clicking the complete lesson button at the bottom of the page the lesson doesn't complete'
    validations:
      required: true
  - type: textarea
    id: reproduction-steps
    attributes:
      label: How to reproduce
      description: A clear set of steps to reproduce the bug. Please include as much detail as possible to help reproduce it.
      placeholder: |
        1. Sign in
        2. Visit a lesson page
        3. Click the complete button
        4. The complete button does not update
    validations:
      required: true
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected behavior
      description: A brief description of what you expected to happen.
      placeholder: |
        1. Sign in
        2. Visit a lesson page
        3. Click the complete button
        4. The complete button updates correctly
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - Other
  - type: dropdown
    id: os
    attributes:
      label: What OS are you using?
      multiple: true
      options:
        - Windows
        - MacOS
        - Ubuntu
        - Android
        - iOS
  - type: input
    id: contact
    attributes:
      label: Discord Name
      description: Optionally provide your discord name to help coordinate changes there if necessary
      placeholder: ex. odinite
    validations:
      required: false
  - type: textarea
    id: additional-comments
    attributes:
      label: Additional Comments
      description: "Anything else you'd like to cover"
      placeholder: We ❤️ open source
    validations:
      required: false
